name: tool_clind_theme
description: tool clind theme package.
publish_to: none

environment:
  sdk: 3.4.0
  flutter: 3.22.0

dependencies:
  flutter:
    sdk: flutter

  core_theme:
    path: ../../../core/theme

dev_dependencies:
  build_runner: 2.4.8
  flutter_gen_runner: 5.4.0

flutter_gen:
  output: lib/gen/
  line_length: 120
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  assets:
    - assets/colors/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.ttf
          weight: 600
