name: e_commerce_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  http: ^1.1.0
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
