name: clind_server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: 3.4.0

dependencies:
  args: 2.4.2
  faker: 2.1.0
  json_annotation: 4.8.1
  shelf: 1.4.1
  shelf_router: 1.1.4
  shelf_swagger_ui: 1.0.0+2

dev_dependencies:
  build_runner: 2.4.8
  http: 1.1.0
  json_serializable: 6.7.1
  lints: 3.0.0