name: ch4_flutter_bloc_firebase_login
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 3.22.0

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: 8.1.3
  equatable: 2.0.5
  firebase_core: 2.27.0
  flow_builder: 0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.4
  font_awesome_flutter: 10.7.0
  form_inputs:
    path: packages/form_inputs
  formz: 0.7.0
  google_fonts: 6.0.0
  meta: 1.12.0

dev_dependencies:
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
