name: authentication_repository
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 3.22.0

dependencies:
  cache:
    path: ../cache
  equatable: 2.0.5
  firebase_auth: 4.17.8
  firebase_core: 2.27.0
  flutter:
    sdk: flutter
  google_sign_in: 6.2.1
  meta: 1.12.0

dev_dependencies:
  flutter_lints: 3.0.1
