name: flutter_bloc_starter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: 3.4.0
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.4

dev_dependencies:
  flutter_lints: 3.0.1
