name: ui
description: clind ui package
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 3.22.0

dependencies:
  domain:
    path: ../domain
  data:
    path: ../data
  presentation:
    path: ../presentation
  di:
    path: ../di
